version: '1.0'
name: first20231220
displayName: test
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - master
variables:
  version: V1.0.0.1
stages:
  - name: stage-e304ec54
    displayName: 安装依赖
    strategy: naturally
    trigger: auto
    executor:
      - zerokit
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# 可以使用pip下载依赖'
          - export PATH="$PATH:$HOME/.local/bin"
          - pip install --upgrade pip
          - python --version
          - cat /etc/os-release
          - yum install -y python39-devel
          - '#chmod +x install_python_dev.sh'
          - '#./install_python_dev.sh'
          - pip install --user -r requirements.txt
          - current_dir=$(pwd)
          - pyinstaller --windowed --add-data "$current_dir/app/config:./app/config" --icon="$current_dir/app/resource/images/logo.png" --target-platform=win64 Assistent.py
          - ''
          - echo "构建完成"
          - ''
          - tar -zcvf "$current_dir/Assistent.tar.gz" "$current_dir/Assistent/*"
          - ' echo "$version"'
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
